### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by CoBoakster** [zastlx/elficia#3]
I don't understand how to use this? What do I do with it? Where do I put it? I need help.

**Comment by microcrit** [comment]
enable devtools in discord's config (or use vencord), open devtools and select the iframe via element inspector, switch to console and paste the built script in the console. alternatively open the iframe's url in your browser and paste elficia in there or run the built script with tampermonkey.

**Comment by dsowders** [comment]
I'm completely new to this. I just downloaded vencord and have an inspect element console I can open but I'm not sure what script to paste in and where.

**Comment by microcrit** [comment]
install dependencies including esbuild, run scripts/build.mjs and the resulting file in dist/elficia.js should be pasted in your console after selecting the iframe the activity is running in

**Comment by zastlx** [comment]
ill make a proper tutorial for running it in discord and in a dev environment soon

**Comment by dsowders** [comment]
> ill make a proper tutorial for running it in discord and in a dev environment soon

Sweet, I'd love to check it out when it's done!

**Comment by Legend-Recalls** [comment]
any update?

**Comment by zastlx** [comment]
> any update?

https://github.com/zastlx/elficia/blob/main/assets/TUTORIAL.md
